Avoid an integer overflow in the pdMS_TO_TICKS macro. Use portTICK_PERIOD_MS as workaround instead.
dbSuS/libpax pull request #28
Opened 2024-09-17 21:12 UTC by commeco

As discussed [here](https://github.com/cyberman54/ESP32-Paxcounter/issues/1022 ), this is a fix to avoid an integer overflow if for example the sendcycle in ESP32-Paxcounter is modified to reach several hours.

Due to the fact, that the minimum report interval is 1 second, a configTICK_RATE_HZ of 125 or lower is also working.

What do you think?

Regards
  Matthias

2024-09-19 20:45 UTC, cyberman54 approved these changes

2024-09-22 12:41 UTC, cyberman54 approved these changes

2025-09-16 22:05 UTC, FlorianLudwig commented on lib/libpax/libpax.cpp
> +#define LIBPAX_MAX_SIZE 0x1FFFF  // full enumeration of uint32_t
```suggestion
#define LIBPAX_MAX_SIZE 0xFFFF +1  // full enumeration of uint16_t
```
I am not sure what the intention is here. The change does not make the bitmap 32bit as far as i can tell.

But indeed there is a bug. The LIP_MAP_SIZE (next line) is off by due to dividing the max u16 number by bits per word, instead of u16 possible values divided by bits per word.

2025-09-21 10:39 UTC, cyberman54 commented on lib/libpax/libpax.cpp
> +#define LIBPAX_MAX_SIZE 0x1FFFF  // full enumeration of uint32_t
It's intentional to store only the last 2 bytes of MAC addresses, not the full MAC. This allows a small 8Kbyte bitmap organized storage. This way there is no need for a costly find / hash routine to find MAC matches.

Yes, LIBPAX_MAX_SIZE is off by 1. This is a bug. Should be fixed.

2025-09-21 10:40 UTC, cyberman54 commented on lib/libpax/libpax.cpp
> +  // if it is a locally administered ("random") mac, we don't count it
It's intentional to count only random MACs. This is feature, not a bug.

2025-09-21 10:45 UTC, cyberman54 requested changes
Please reduce / edit the PR as stated in the comments. Thanks.

2025-09-21 17:44 UTC, cyberman54 commented on lib/libpax/libpax.cpp
> +#define LIBPAX_MAX_SIZE 0x1FFFF  // full enumeration of uint32_t
I tried it, but doesn't work.
`#define LIBPAX_MAX_SIZE 0xFFFF +1  // full enumeration of uint16_t`
leads to
_region `dram0_0_seg' overflowed by 181752 bytes_

2025-09-22 06:14 UTC, commeco commented
> Please reduce / edit the PR as stated in the comments. Thanks.

I'm sorry, it's my fault. I didn't want to push that as a PR. In my Repo i pushed to my master branch, but my first PR from last year was also my master branch. :-(

The changes of the last weeks were internal testing from my side.

2025-09-23 13:23 UTC, cyberman54 commented
This can be closed. I transferred the reviewed and validated changes in a new PR, now pending for merge.

2025-09-23 14:56 UTC, philbuettner commented
Already solved in #31

2025-09-23 14:56 UTC, closed without merging